# Site settings
title: Introduction to Artificial Intelligence
subtitle: Iran University of Science and Technology
description: |
    Instructor: Mohammad Taher Pilehvar

message: Register to our Google <a href="https://groups.google.com/forum/#!forum/ai97">groups page</a> to get course notifications via email.
baseurl: "ai97" # the subpath of your site, e.g. /blog/
url: "http://iust-courses.github.io/ai97/" # the base hostname & protocol for your site
#syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/svm-rmarkdown-syllabus-example.pdf"
#githubdir: "svmiller/course-website"

# Author/user information
email: pilehvar@iust.ac.ir
#twitter_username: 
github_username:  pilehvar
authorurl: "http://pilevar.com/taher/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
