# Site settings
title: Course Website
subtitle: Title of the Course
description: |
    Introduction to Artificial Intelligence
    
    Iran University of Science and Technology
    
    Instructor: Mohammad Taher Pilehvar
    
    Please join our Google groups at:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://course-website.svmiller.com" # the base hostname & protocol for your site
syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/svm-rmarkdown-syllabus-example.pdf"
githubdir: "svmiller/course-website"

# Author/user information
email: svmille@clemson.edu
twitter_username: stevenvmiller
github_username:  svmiller
authorurl: "http://svmiller.com"
address: |
    Department of Political Science
    232 Brackett Hall
    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
